HW packer-base
Otus-DevOps-2023-01/fill1986_infra pull request #4
Opened 2023-03-12 19:18 UTC by fill1986

# Выполнено ДЗ № 7

 - [V] Основное ДЗ
 - [V] Задание со *

## В процессе сделано:
В директории /packer создан файл (Packer шаблон) ubuntu16.json содержащий описание для сборки обаза VM с предустановленными Ruby и MongoDB
 - на локальной машине установлен Packer
 - создан шаблон ubuntu16.json для создания образа в Yandex Cloud
 - для добавления Ruby и MongoDB в образ, были добавлены соответствующие срипты в раздел provisioners шаблона ubuntu16.json
 - дополнительно создан шаблон для создания bake-образа включающий все зависимости приложения и сам код приложения
 - дополнительно создан скрипт create-reddit-vm.sh в директории config-
scripts, который создает ВМ с помощью Yandex.Cloud CLI.

## Как запустить проект:
$git clone https://github.com/Otus-DevOps-2023-01/fill1986_infra.git
# cd packer
$ packer build -var-file=scripts/variables.json.examples ./immutable.json
$ ./config-scripts/create-reddit-vm.sh

## Как проверить работоспособность:
Перейти по ссылке http://IP_VM:9292 и проверить доступность приложения

## PR checklist
 - [V] Выставил label с номером домашнего задания
 - [V] Выставил label с темой домашнего задания

2023-03-13 11:57 UTC, mrgreyves requested changes
Здравствуйте!)
У вас в WF добавлен только auto_assign
А вот тесты видимо пропустили =(
Нужно их добавить
Так же по пакеру, нужно добавить фейковый ключ что бы пакер смог проверить конфигурацию

2023-03-21 16:28 UTC, mrgreyves requested changes
Здравствуйте!)
Нужно внести небольшие правки
Оставил комментарий к файлу =)

2023-03-21 16:28 UTC, mrgreyves commented on packer/immutable.json
> +            "max_retries": 2
Что-то эту опцию пакер не знает
Нужно удалить ее из конфигурации

2023-03-21 17:58 UTC, fill1986 commented on packer/immutable.json
> +            "max_retries": 2
Спасибо, не сразу увидел на какой ключ рунается)
Тесты прошли.

2023-03-22 13:18 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2023-03-22 17:17 UTC, merged